### ISSUE TITLE
Allow Interface Definition via Configuration

### ISSUE THREAD

**Issue by solverat** [karser/PayumSaferpay#1]
For Example: 

```yaml
payum:
    gateways:
        saferpay:
            interface: 'PAYMENT_PAGE' 
```
If you're using this extension within a given (CMS/Framework), you may not able to set configuration data via `setDetails()`. In my opinion its also a better place to define such "core configuration things" via gateway config instead of payment detail configuration.
